#CC	= mpicxx
#OPTS	= -O3 -DWRITE_OTF2_TRACE=1 -DSCOREP_USER_ENABLE
#INCS	= -I${SCOREP_INSTALL}/include -I${SCOREP_INSTALL}/include/scorep

CC	= /g/g92/jain6/scratch-f/network-sim/charm/mpi-linux-x86_64-bigemulator/bin/ampicxx
OPTS	= -O2
INCS	= 


