#!/bin/bash

#runjob -p 2 -n 512  --block $COBALT_PARTNAME --envs BG_SHAREDMEMSIZE=32MB BGQ_COUNTER_FILE=$mapping.cnt --mapping $mapping --envs PAMI_ROUTING=[2048][,[4][,[0:4][,[2][,2]]]] : ./proofdef 1048576 0 1 -1 -1
size=1
for i in {1..20}
do
runjob -p 1 -n 2 --block $COBALT_PARTNAME --envs BG_SHAREDMEMSIZE=32MB : ./ping 0 1 $size 1 >out_$size
echo "Next" >>out_$size
runjob -p 1 -n 2 --block $COBALT_PARTNAME --envs BG_SHAREDMEMSIZE=32MB : ./ping 0 1 $size 10 >>out_$size
echo "Next" >>out_$size
runjob -p 1 -n 2 --block $COBALT_PARTNAME --envs BG_SHAREDMEMSIZE=32MB : ./ping 0 1 $size 100 >>out_$size
echo "Next" >>out_$size
runjob -p 1 -n 2 --block $COBALT_PARTNAME --envs BG_SHAREDMEMSIZE=32MB : ./ping 0 1 $size 1000 >>out_$size
let "size = 2 * $size"
done
